# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: engine_status.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("engine_status.proto", :syntax => :proto3) do
    add_message "engine_data.EngineStatus" do
      optional :rpm, :float, 1
      optional :temp, :float, 2
      optional :oil_pressure, :float, 3
      optional :gear, :int32, 4
      optional :speed, :float, 5
    end
  end
end

module EngineData
  EngineStatus = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("engine_data.EngineStatus").msgclass
end
